# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NDAVqxMGG9ZprWqGIuIvjpZdW1NlyFT
"""

from flask import Flask, jsonify
import json

app = Flask(__name__)
@app.route("/")
def home():
    return "✅ News Sentiment Classifier is Live!"

@app.route("/news", methods=["GET"])
def get_articles():
    try:
        with open("articles_json.json", "r", encoding="utf-8") as f:
            data = json.load(f)
        return jsonify(data)
    except Exception as e:
        return jsonify({"error": str(e)})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)